language: node_js
node_js:
  - "0.10"
before_install:
  - "echo 'test started'"
before_script:
script:
env:
  global:
  #
  # Keys:
  #
  #BH_APP_DEV_USER_KEY
  - secure: "U+GeYP8rFzrr1smoyk0LK2C9+s0bdxSi7J6b079gJ/qpy/weNd4lIqS13IA/wql9kLSvMFCln2F/L7tslupIklWlQzs1mA+dRKPlCpFwyDvGu2U5fu1K5iEBlYMhPXc9qoXLtankNmjzG/uHRaI1LKbZH4duv0FVQhOPbqD9yCo="
  #BH_APP_DEV_USER_SECRET
  - secure: "imttjILPTWTsl8cQU0qztwDYwsz6jc42cr+7Pe+jQJdP4YAw/KmTdXW6LzPE/cUzVPylgIclZksxGgJZW2U1zYHhhpq8lB2S7mi4FsTMAFZu9xJT5ZZp8yt3R7Iq/qBJueU+Xm3QI6aoLBrNSH3IysCj621ZGWk4aNk/ZksUCdw="
after_success:
  - "echo $BH_ENV"
  - ".elasticbeanstalk/deploy.sh $BH_APP_USER_KEY $BH_APP_USER_SECRET"
  - "echo '[the end]'"
#branches:
#  only:
#  - develop
#  - master
#deploy:
#  provider: opsworks
#  access-key-id: $BH_APP_USER_KEY
#  secret-access-key: $BH_APP_USER_SECRET
#  app-id: 3c33e8bd-9e9f-43ff-86ab-e8c81588180e
#  on:
#    all_branches: true
