language: node_js
node_js:
  - "0.10"
before_install:
  - "echo 'test started'"
before_script:
  - zip bh-app.zip * && mkdir bin && mv bh-app.zip bin/bh-app.zip
script:
env:
  global:
  #
  # Keys:
  #
  #BH_APP_DEV_USER_KEY
  - secure: "Ej/Fz3fJ7MbWGWzvZKB9ruPnCZQ7qDVZwD97TQEXmVUorEGwQtU8XwW7jHeRVOa3QHXo9XiaSXLQEeT1ujm6aFuk08w18rGXkoZJCq5pZ0bkf+VvTmUS9TF3cbMhq/qwpEWkjcSdcVuS6HPFhvQS/J7mOAiQN5CdqfCVxEozNAY="
  #BH_APP_DEV_USER_SECRET
  - secure: "XKQieu4A7W1nDHE0EdDohafgM8dA2EfZx8UxG5IE9IEmEPm90ugTU8uiGruCpDhp/7NPg/YNVQoSeo4w5KwJsBIPEV6bJNXoOke10QRuEGr4EJJg8DIodgtu7Es87cvKW4YTQNC8k3JZqPpUowaVlhCX8XMXk7Pf567oIdDBE0U="
after_success:
  - "echo '[the end]'"
#branches:
#  only:
#  - develop
#  - master
deploy:
  provider: s3
  access_key_id: $BH_APP_DEV_USER_KEY
  secret_access_key: $BH_APP_DEV_USER_SECRET
  bucket: "bh-artifacts"
  local-dir: bin
#  provider: opsworks
#  access-key-id: $BH_APP_DEV_USER_KEY
#  secret-access-key: $BH_APP_DEV_USER_SECRET
#  app-id: 3c33e8bd-9e9f-43ff-86ab-e8c81588180e
#  on:
#    all_branches: true
